
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - my-network
  
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped
    depends_on:
    - zookeeper
    networks:
      - my-network
  kafka-init:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - kafka 
    entrypoint:
      - sh
      - -c 
      - |
        until kafka-topics --bootstrap-server kafka:9092 --list
        kafka-topics --create --topic chat-messages --partitions 1 --replication-factor 1 --if-not-exists --bootstrap-server kafka:9092    
    networks:
      - my-network

  db:
    image: postgres:latest
    container_name: postgres_cont
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network
  

  app:
    build:
      context: .
      dockerfile: Dockerfile 
    env_file:
      - .env

    ports:
    - "44044:44044"
    restart: unless-stopped
    command: ["./chat_service","--config=/config/local.yaml"]
    depends_on:
     - kafka
     - db
    
    volumes:
      - ./config:/config:ro
    networks:
      - my-network
      

volumes:
  pgdata:

networks:
  my-network:
    driver: bridge

 
