
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - my-network
  
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped
    depends_on:
    - zookeeper
    networks:
      - my-network

  db:
    image: postgres:latest
    container_name: postgres_container1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network
   
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
    - "8080:8080"
    restart: unless-stopped
    command: ["./chat_service","--config=/config/local.yaml"]
    depends_on:
     - kafka
     - db
    volumes:
      - ./config:/config:ro
    networks:
      - my-network
      

volumes:
  pgdata:

networks:
  my-network:
    driver: bridge

 
